name: webview
description: Dart bindings for webview, a tiny library for creating web-based desktop GUIs.
version: 1.0.0-dev.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0-0 <3.0.0'


dev_dependencies:
  lints: ^1.0.1
  stack_trace: ^1.10.0
dependencies: 
  ffi: ^1.1.2
